### ISSUE TITLE
Scroll To Top/Bottom Buttons Not Working on Gmail Mobile Website

### ISSUE THREAD

**Issue by Siva981** [KristhianX/essential-buttons-toolbar#37]
**Android & Device:**
Android 12 (Samsung Galaxy M01)

**Firefox For Android:**
130.0.1 (Latest Version available at the time of creating this issue)

**Issue:**
The Scroll To Down/Top feature has stopped working on the Gmail mobile website. It was working flawlessly before.

**Issue Page URL:**
https://mail.google.com/mail/mu/mp/465/#tl/Inbox

**Possible Rootcause:**
Google recently made a change to the options bar at the top a few days ago. This bar (the one that says Inbox in the screenshots) is the one  at the topmost of the page, which houses the Menu button on it's left corner & the red colored Compose button on it's right corner. When the page was scrolled down, this bar used to move up with the page (it got hidden or something?) and not appear again until we scroll to the top of the page again. But now, Google has made it such that this bar stays put when the rest of the page is scrolled down. Now it stays put even after opening an email. Previously the behavior was the same as that of the Inbox.

**Note:**
All the other buttons of your EBTB Addon is still working on the Inbox page & the Email page. It is just the Scroll buttons that have stopped working.

**Sreenshots:**

1) Inbox Page

![Screenshot_20240929-040252_Firefox](https://github.com/user-attachments/assets/fe218f57-3c9b-4a5a-b733-b8c3b4cbae3d)

2) Email Page

![Screenshot_20240929-042338_Firefox](https://github.com/user-attachments/assets/3924b627-3edd-47cf-9814-ed583a2febac)

**Comment by KristhianX** [comment]
Hi! Thanks for your detailed bug report, and sorry for the late reply. I’ve been quite busy with work, but I hope to find some time soon to make the necessary updates to the add-on.

The code for scrolling to the top and bottom of pages is simple and should work on most sites, but it depends on those sites having a traditional layout. Sites with different layouts or that make changes like the one you mentioned won’t work with that code. I’ll need to implement a different approach in such cases. I’ll keep you updated on any changes.

Thanks again for your feedback!

**Comment by KristhianX** [comment]
Hi! This has been fixed in the new 1.8.1 version. Thanks again for your feedback.

**Comment by Siva981** [comment]
Hi,

This issue still persists on my Android 12 (Samsung Galaxy M01).

Do you need a screen recording? Or any other debug info that could help?

Thank you.

**Comment by KristhianX** [comment]
I think I know what is happening. I'll test another approach and let you know when it's ready.

**Comment by KristhianX** [comment]
Hi! The new update (1.8.2) is now available on AMO. Please test if the code is working properly after you receive the update. In my tests, it works as expected on the inbox page and in email view, but I haven't tested other views. Thank you for your feedback!

**Comment by Siva981** [comment]
Hi,

Unfortunately, the results are still the same for me even after the version got updated to 1.8.2 on my Samsung Galaxy M01 (Android 12). It is not working on either the Inbox page or the Email view.

Thank you.

**Comment by KristhianX** [comment]
Hello! Thank you for your reply and patience. Could you please try disabling other extensions to ensure there are no conflicts? If the problem still persists, please let me know, and I will add an option or button in the next update to log the result of the code so you can send me those logs.

**Comment by Siva981** [comment]
Hi,

I believe you are onto something here. It is uBlock Origin. That is what is bothering with the scroll the functionality. When I disabled all the addons & then re-enabled EBTB alone, the scroll started working on mail.google.com to my surprise. 

So turned back on the other addons one by one (I use 13) & narrowed it down to uBlock. Now I do not even have to disable Ublock altogether. Disabling it just for mail.google.com makes the scroll work again on Gmail.

That said, I'm quite not sure if it is any particular filter inside uBlock that is blocking EBTB's scroll functionality. I did unselect a few filters at a time (including My Filters), applied changes & then reloaded mail.google.com. But that did not help me identify if it is any particular filter that is causing this.

Do you need a screenshot of my uBlock's dashboard? So that you could apply all the same filters that I'm using and recreate the issue?

**Comment by KristhianX** [comment]
Thank you for your reply and for taking the time to test the behavior with other add-ons disabled. I’m also a user of uBlock Origin—it’s a must-have! 

I was busy today fixing some bugs from the last update. Please provide a screenshot or detail any changes you’ve made to the default uBlock settings, especially those that apply to Gmail, and I’ll investigate it tomorrow.

**Comment by Siva981** [comment]
Hi,

I spent some time today digging into my uBlock's filters. I managed to narrow it down to 4 of the filters that I am using, which I believe are causing this. All of them seemingly points to something. It is the "Upgrade to a smarter Gmail" banner (refer screenshot) that appears at the top of all the pages on mail.google.com when these filters are not enabled.

As soon as I enable any of these 4 filters, they are blocking this banner from being displayed on mail.google.com. And unfortunately, as long as this annoying banner is displayed at the top of the page, EBTB's scroll works. Once it is blocked/hidden by any of these 4 filters, the scroll stops working.

Here are the 4 Filters and links to their code. Hopefully you could figure out a way to get around this! 🤞

1) EasyList – Notifications

https://ublockorigin.github.io/uAssetsCDN/thirdparties/easylist-notifications.txt

2) AdGuard – Mobile App Banners

https://filters.adtidy.org/extension/ublock/filters/20.txt

3) AdGuard Annoyances filter  (Custom Filter)

https://filters.adtidy.org/extension/ublock/filters/14.txt

4) Fanboy's Annoyance List  (Custom Filter)

https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt

**Banner:**

![Screenshot_20241114-062754_Firefox](https://github.com/user-attachments/assets/5996f9a1-7f1b-4f84-9cf1-5e5605f7c608)

**Comment by KristhianX** [comment]
Thank you for identifying the exact cause; it made the problem much easier to investigate.

I was able to reproduce the issue and modified the code to correctly detect the scrollable element. The fix will be included in the next version, and I'll let you know once it's uploaded.

Thanks for your feedback and patience.

**Comment by KristhianX** [comment]
Hi! The update is now available in the AMO store. When you receive the update, please check if the buttons are working correctly. There should be no need to modify anything in the uBlock settings.

**Comment by Siva981** [comment]
Hi,

Good news!

I received 1.8.5 today, and the scroll is working again now on the Inbox view, Email view, and also on the Menu view (the one at the top left, which when clicked displays links to all the 
different views like Inbox, Sent Mail, Drafts, etc,., and as well the list of all the labels that we've set up on Gmail).

Thank you for religiously following this up & working to resolve it! 🙏
